# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbg484-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/alvin/Documents/UT Austin/Senior 2.0/VLSI_Testing/project2/project_2_vivado/project_2_vivado.cache/wt} [current_project]
set_property parent.project_path {C:/Users/alvin/Documents/UT Austin/Senior 2.0/VLSI_Testing/project2/project_2_vivado/project_2_vivado.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/alvin/Documents/UT Austin/Senior 2.0/VLSI_Testing/project2/scan_cut.v}
  {C:/Users/alvin/Documents/UT Austin/Senior 2.0/VLSI_Testing/project2/project.v}
  {C:/Users/alvin/Documents/UT Austin/Senior 2.0/VLSI_Testing/project2/testbench.v}
}
read_xdc {{C:/Users/alvin/Documents/UT Austin/Senior 2.0/VLSI_Testing/project2/project_2_vivado/project_2_vivado.srcs/constrs_1/imports/xc7k70tfbg484-2/bft_full.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/alvin/Documents/UT Austin/Senior 2.0/VLSI_Testing/project2/project_2_vivado/project_2_vivado.srcs/constrs_1/imports/xc7k70tfbg484-2/bft_full.xdc}}]

synth_design -top TOP_ctl -part xc7k70tfbg484-2
write_checkpoint -noxdef TOP_ctl.dcp
catch { report_utilization -file TOP_ctl_utilization_synth.rpt -pb TOP_ctl_utilization_synth.pb }
